# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
# do this before all your .NET Core tasks

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.400' 
- task: NuGetToolInstaller@0
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-c release -r osx-x64 -o $(Build.ArtifactStagingDirectory)'
    feedsToUse: 'select'
    versioningScheme: 'off'
    workingDirectory: 'osx'
    projects: 'CdfTools/*.csproj'
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: GitHubRelease@0
  inputs:
    gitHubConnection: GitHubPAT
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: 'v$(MajorVersion).$(MinorVersion).$(PatchVersion)'
    title: 'CdfTools'
    addChangeLog: true
    isDraft: true    